#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Cleaning and feature preparation for stock time-series data."""

import os
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

from utils.logger import setup_logger

logger = setup_logger(__name__)


class DataProcessor:
    """Prepare stable, leakage-safe input data for the ML pipeline."""

    PRICE_COLUMNS = ["Open", "High", "Low", "Close", "Volume"]

    def __init__(self):
        self.scalers: Dict[str, MinMaxScaler] = {}
        self.feature_columns = []
        logger.info("DataProcessor initialized")

    def clean_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """Clean and validate OHLCV data without mutating the input frame."""
        if df is None or df.empty:
            return pd.DataFrame(columns=list(df.columns) if df is not None else [])

        cleaned = df.copy()
        if "Date" not in cleaned.columns:
            raise ValueError("Stock data must contain a Date column")

        cleaned["Date"] = pd.to_datetime(cleaned["Date"], errors="coerce")
        cleaned = cleaned.dropna(subset=["Date"])
        cleaned = cleaned.sort_values("Date")
        cleaned = cleaned.drop_duplicates(subset=["Date"], keep="last")

        present = [column for column in self.PRICE_COLUMNS if column in cleaned]
        if not present:
            raise ValueError("Stock data has no OHLCV columns")

        for column in present:
            cleaned[column] = pd.to_numeric(cleaned[column], errors="coerce")
            if cleaned[column].notna().sum() == 0:
                raise ValueError(f"Column {column} contains no numeric values")
            cleaned[column] = cleaned[column].interpolate(limit_direction="both")

        price_columns = [
            column for column in ["Open", "High", "Low", "Close"]
            if column in cleaned
        ]
        if price_columns:
            cleaned = cleaned[(cleaned[price_columns] > 0).all(axis=1)]
        if "Volume" in cleaned:
            cleaned = cleaned[cleaned["Volume"] >= 0]
        if {"High", "Low"}.issubset(cleaned):
            cleaned = cleaned[cleaned["High"] >= cleaned["Low"]]
        if {"Open", "High", "Low", "Close"}.issubset(cleaned):
            cleaned = cleaned[
                (cleaned["High"] >= cleaned["Open"])
                & (cleaned["High"] >= cleaned["Close"])
                & (cleaned["Low"] <= cleaned["Open"])
                & (cleaned["Low"] <= cleaned["Close"])
            ]

        cleaned = cleaned.replace([np.inf, -np.inf], np.nan)
        cleaned = cleaned.dropna(subset=present)
        cleaned = cleaned.reset_index(drop=True)
        logger.info("Cleaned %s stock data rows", len(cleaned))
        return cleaned

    def fit_scale(self, df: pd.DataFrame, symbol: str) -> pd.DataFrame:
        """Fit a MinMaxScaler on the provided training frame only (legacy compatibility)."""
        cleaned = self.clean_data(df)
        columns = [column for column in self.PRICE_COLUMNS if column in cleaned]
        if not columns:
            raise ValueError("No numeric feature columns available for scaling")
        scaler = MinMaxScaler()
        result = cleaned.copy()
        result[columns] = scaler.fit_transform(result[columns])
        self.scalers[symbol.upper()] = scaler
        self.feature_columns = columns
        return result

    def add_technical_indicators(
        self, df: pd.DataFrame, drop_na: bool = True
    ) -> pd.DataFrame:
        """
        Calculate technical indicators with strictly historical values (no lookahead bias).
        
        Args:
            df: Input DataFrame with at least Date, Open, High, Low, Close, Volume.
            drop_na: If True, drops initial rows containing NaN generated by rolling windows.
            
        Returns:
            DataFrame with enriched technical indicator features.
        """
        cleaned = self.clean_data(df)
        if len(cleaned) < 55 and drop_na:
            logger.warning("Data length (%d) is short for 50-period indicators", len(cleaned))

        data = cleaned.copy()
        close = data["Close"]
        high = data["High"]
        low = data["Low"]
        volume = data["Volume"]

        # --- 1. Xu hướng (Trend Indicators) ---
        data["SMA_10"] = close.rolling(window=10).mean()
        data["SMA_20"] = close.rolling(window=20).mean()
        data["SMA_50"] = close.rolling(window=50).mean()

        data["EMA_12"] = close.ewm(span=12, adjust=False).mean()
        data["EMA_26"] = close.ewm(span=26, adjust=False).mean()

        # --- 2. Động lượng (Momentum Indicators) ---
        # RSI 14
        delta = close.diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)
        avg_gain = gain.rolling(window=14).mean()
        avg_loss = loss.rolling(window=14).mean()
        rs = avg_gain / (avg_loss + 1e-9)
        data["RSI_14"] = 100 - (100 / (1 + rs))

        # MACD (12, 26, 9)
        data["MACD"] = data["EMA_12"] - data["EMA_26"]
        data["MACD_Signal"] = data["MACD"].ewm(span=9, adjust=False).mean()
        data["MACD_Hist"] = data["MACD"] - data["MACD_Signal"]

        # Stochastic Oscillator (%K 14, %D 3)
        low_14 = low.rolling(window=14).min()
        high_14 = high.rolling(window=14).max()
        data["Stoch_K"] = 100 * ((close - low_14) / (high_14 - low_14 + 1e-9))
        data["Stoch_D"] = data["Stoch_K"].rolling(window=3).mean()

        # --- 3. Biến động (Volatility Indicators) ---
        # Bollinger Bands (20, 2)
        bb_middle = close.rolling(window=20).mean()
        bb_std = close.rolling(window=20).std()
        data["BB_Middle"] = bb_middle
        data["BB_Upper"] = bb_middle + (2 * bb_std)
        data["BB_Lower"] = bb_middle - (2 * bb_std)
        data["BB_Width"] = (data["BB_Upper"] - data["BB_Lower"]) / (bb_middle + 1e-9)
        data["BB_Pct"] = (close - data["BB_Lower"]) / (data["BB_Upper"] - data["BB_Lower"] + 1e-9)

        # ATR 14
        prev_close = close.shift(1)
        tr1 = high - low
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        data["ATR_14"] = tr.rolling(window=14).mean()

        # --- 4. Giá & Khối lượng (Price Action & Volume) ---
        data["Daily_Return"] = close.pct_change()
        data["Log_Return"] = np.log(close / (prev_close + 1e-9))
        data["HL_Spread"] = (high - low) / (close + 1e-9)

        vol_sma_20 = volume.rolling(window=20).mean()
        data["Volume_SMA_20"] = vol_sma_20
        data["Volume_Ratio"] = volume / (vol_sma_20 + 1e-9)

        if drop_na:
            data = data.dropna().reset_index(drop=True)

        return data

    def fit_scalers(
        self,
        train_df: pd.DataFrame,
        feature_cols: list,
        target_col: str = "Close",
        symbol: str = "DEFAULT",
    ) -> None:
        """
        Fit feature and target scalers strictly on the training set to prevent leakage.
        """
        if train_df is None or train_df.empty:
            raise ValueError("Training DataFrame cannot be empty for fitting scalers")

        missing_features = [col for col in feature_cols if col not in train_df.columns]
        if missing_features:
            raise ValueError(f"Missing feature columns in training data: {missing_features}")
        if target_col not in train_df.columns:
            raise ValueError(f"Target column '{target_col}' not found in training data")

        feature_scaler = MinMaxScaler(feature_range=(0, 1))
        feature_scaler.fit(train_df[feature_cols])

        target_scaler = MinMaxScaler(feature_range=(0, 1))
        target_scaler.fit(train_df[[target_col]])

        sym_key = symbol.upper().strip()
        self.scalers[sym_key] = {
            "feature_scaler": feature_scaler,
            "target_scaler": target_scaler,
            "feature_cols": list(feature_cols),
            "target_col": target_col,
        }
        logger.info(
            "Fit scalers for symbol '%s' with %d features on %d rows",
            sym_key,
            len(feature_cols),
            len(train_df),
        )

    def transform(self, df: pd.DataFrame, symbol: str = "DEFAULT") -> pd.DataFrame:
        """
        Transform a dataset using previously fitted scalers.
        """
        sym_key = symbol.upper().strip()
        if sym_key not in self.scalers or not isinstance(self.scalers[sym_key], dict):
            raise KeyError(f"No fitted scalers found for symbol '{sym_key}'. Call fit_scalers first.")

        scaler_info = self.scalers[sym_key]
        feature_scaler = scaler_info["feature_scaler"]
        target_scaler = scaler_info["target_scaler"]
        feature_cols = scaler_info["feature_cols"]
        target_col = scaler_info["target_col"]

        result = df.copy()
        result[feature_cols] = feature_scaler.transform(result[feature_cols])
        # Only scale target separately if it is not already transformed as part of feature_cols
        if target_col in result.columns and target_col not in feature_cols:
            result[[target_col]] = target_scaler.transform(result[[target_col]])

        return result

    def transform_target(self, y: np.ndarray, symbol: str = "DEFAULT") -> np.ndarray:
        """
        Transform target values using the fitted target scaler.
        """
        sym_key = symbol.upper().strip()
        if sym_key not in self.scalers or not isinstance(self.scalers[sym_key], dict):
            raise KeyError(f"No fitted scalers found for symbol '{sym_key}'.")

        target_scaler = self.scalers[sym_key]["target_scaler"]
        arr = np.array(y, dtype=float)
        orig_shape = arr.shape

        if arr.ndim == 1:
            return target_scaler.transform(arr.reshape(-1, 1)).reshape(orig_shape)
        elif arr.ndim == 2:
            scaled = np.zeros_like(arr, dtype=float)
            for step in range(arr.shape[1]):
                scaled[:, step] = target_scaler.transform(arr[:, [step]]).flatten()
            return scaled
        else:
            raise ValueError(f"Unsupported array dimension: {arr.ndim}")

    def inverse_transform_target(
        self, y_scaled: np.ndarray, symbol: str = "DEFAULT"
    ) -> np.ndarray:
        """
        Reverse scale predictions or target values back to their original monetary scale.
        """
        sym_key = symbol.upper().strip()
        if sym_key not in self.scalers or not isinstance(self.scalers[sym_key], dict):
            raise KeyError(f"No fitted scalers found for symbol '{sym_key}'.")

        target_scaler = self.scalers[sym_key]["target_scaler"]
        arr = np.array(y_scaled)
        orig_shape = arr.shape

        if arr.ndim == 1:
            arr_2d = arr.reshape(-1, 1)
            inversed = target_scaler.inverse_transform(arr_2d)
            return inversed.reshape(orig_shape)
        elif arr.ndim == 2:
            # Multi-horizon (e.g., T+1...T+5)
            inversed = np.zeros_like(arr, dtype=float)
            for step in range(arr.shape[1]):
                inversed[:, step] = target_scaler.inverse_transform(arr[:, [step]]).flatten()
            return inversed
        else:
            raise ValueError(f"Unsupported array dimension: {arr.ndim}")

    def create_sequences(
        self,
        df: pd.DataFrame,
        feature_cols: list,
        target_col: str = "Close",
        lookback: int = 30,
        horizon: int = 5,
    ) -> tuple:
        """
        Generate time-series sliding window sequences for multi-step forecasting.
        
        Args:
            df: Normalized/transformed DataFrame ordered by Date ascending.
            feature_cols: List of column names used as input features.
            target_col: Target column name to forecast.
            lookback: Number of past timesteps (L).
            horizon: Number of future timesteps (H).
            
        Returns:
            Tuple of (X, y, dates):
                - X: np.ndarray shape (N, lookback, len(feature_cols))
                - y: np.ndarray shape (N, horizon) if horizon > 1 else (N,)
                - dates: pd.Series of the forecast trigger dates (date at index t).
        """
        if df is None or len(df) < (lookback + horizon):
            raise ValueError(
                f"DataFrame length ({len(df) if df is not None else 0}) must be >= lookback ({lookback}) + horizon ({horizon})"
            )

        features_matrix = df[feature_cols].values
        target_vector = df[target_col].values
        date_series = df["Date"] if "Date" in df.columns else pd.Series(range(len(df)))

        X_list = []
        y_list = []
        dates_list = []

        total_samples = len(df) - lookback - horizon + 1
        for i in range(total_samples):
            # Window covers [i : i + lookback]
            X_list.append(features_matrix[i : i + lookback])
            # Horizon covers [i + lookback : i + lookback + horizon]
            if horizon == 1:
                y_list.append(target_vector[i + lookback])
            else:
                y_list.append(target_vector[i + lookback : i + lookback + horizon])
            # Date at prediction anchor point
            dates_list.append(date_series.iloc[i + lookback - 1])

        X = np.array(X_list, dtype=np.float32)
        y = np.array(y_list, dtype=np.float32)
        dates = pd.Series(dates_list, name="Date")

        return X, y, dates

    def save_scalers(self, file_path: str) -> None:
        """Persist fitted scalers to a joblib file."""
        os.makedirs(os.path.dirname(os.path.abspath(file_path)), exist_ok=True)
        joblib.dump(self.scalers, file_path)
        logger.info("Saved %d scaler profiles to %s", len(self.scalers), file_path)

    def load_scalers(self, file_path: str) -> None:
        """Load fitted scalers from a joblib file."""
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Scaler file not found: {file_path}")
        self.scalers = joblib.load(file_path)
        logger.info("Loaded %d scaler profiles from %s", len(self.scalers), file_path)

